USE app;

CREATE TABLE State (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    STATE CHAR(2) NOT NULL,
    STATE_NAME VARCHAR(60),
    STATUS_CODE CHAR(3),
    STATUS_DESCRIPTION VARCHAR(60),
    AVERAGE_RESPONSE TINYINT,
    EXPECTED_RETURN DATETIME,
    OBSERVATION VARCHAR(255),
    UPDATED_TIME DATETIME
);

ALTER TABLE State
ADD CONSTRAINT State_Unique UNIQUE (STATE);
